# Generated by Django 4.0.10 on 2023-03-01 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'answer', 'verbose_name_plural': 'answers'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('-created',), 'verbose_name': 'test', 'verbose_name_plural': 'tests'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='npp',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='npp',
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='quiz',
            table=None,
        ),
    ]
