# Generated by Django 4.0.10 on 2023-03-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_answer_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('npp',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('npp',), 'verbose_name': 'test', 'verbose_name_plural': 'tests'},
        ),
        migrations.AddField(
            model_name='category',
            name='npp',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sort'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='npp',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sort'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='quiz',
            table='quiz',
        ),
    ]
