# Generated by Django 4.0.10 on 2023-03-02 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_category_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-npp',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('-npp',), 'verbose_name': 'test', 'verbose_name_plural': 'tests'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
